"""
generate_signal_correlations.py
================================
Counts co-occurrence of signal pairs across all posts and writes the result
to _data/signal_correlations.yml. Run by the aggregate workflow after
update_signal_status.py.

Strength tiers:
  strong  : >= 6 co-occurrences
  moderate: >= 3
  weak    : >= 1
"""

import sys
from collections import defaultdict
from itertools import combinations
from pathlib import Path

SIGNALS_FILE      = Path("_data/signals.yml")
POSTS_DIR         = Path("_posts")
CORRELATIONS_FILE = Path("_data/signal_correlations.yml")


def parse_front_matter(text: str) -> dict:
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}
    fm = {}
    for line in text[4:end].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        fm[key.strip()] = value.strip()
    return fm


def parse_inline_list(value: str) -> list[str]:
    cleaned = (value or "").strip()
    if not cleaned.startswith("[") or not cleaned.endswith("]"):
        return []
    return [item.strip().strip('"').strip("'") for item in cleaned[1:-1].split(",") if item.strip()]


def load_signal_ids() -> list[str]:
    ids = []
    for line in SIGNALS_FILE.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("- id:"):
            ids.append(stripped.split(":", 1)[1].strip().strip('"').strip("'"))
    return ids


def strength_label(count: int) -> str:
    if count >= 6:
        return "strong"
    if count >= 3:
        return "moderate"
    return "weak"


def main() -> int:
    signal_ids = set(load_signal_ids())
    pair_counts: dict[tuple[str, str], int] = defaultdict(int)

    for path in POSTS_DIR.glob("*.md"):
        fm = parse_front_matter(path.read_text(encoding="utf-8"))
        if fm.get("article_type", "").strip('"') == "theory":
            continue
        ids = [s for s in parse_inline_list(fm.get("signal_ids", "")) if s in signal_ids]
        if len(ids) < 2:
            continue
        for a, b in combinations(sorted(ids), 2):
            pair_counts[(a, b)] += 1

    # Sort by co-occurrence count descending
    sorted_pairs = sorted(pair_counts.items(), key=lambda x: x[1], reverse=True)

    lines = ["# Auto-generated by generate_signal_correlations.py — do not edit manually\n"]
    lines.append("correlations:\n")
    for (a, b), count in sorted_pairs:
        lines.append(f"  - signal_a: {a}\n")
        lines.append(f"    signal_b: {b}\n")
        lines.append(f"    co_occurrences: {count}\n")
        lines.append(f"    strength: {strength_label(count)}\n")

    CORRELATIONS_FILE.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {len(sorted_pairs)} signal pairs → {CORRELATIONS_FILE}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
