ALTER TABLE articles ADD COLUMN IF NOT EXISTS relevance_score integer;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS research_domain text;

UPDATE articles SET relevance_score = 3, research_domain = 'sociolinguistics' WHERE slug = '2026/01/30/a-life-of-science';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/01/30/allocutivity-and-the-syntax-of-honorifics';
UPDATE articles SET relevance_score = 4, research_domain = 'semantics' WHERE slug = '2026/01/30/causation-and-causal-relations-insights-from-natural-languag';
UPDATE articles SET relevance_score = 4, research_domain = 'computational linguistics' WHERE slug = '2026/01/30/computational-methods-for-language-documentation-and-descrip';
UPDATE articles SET relevance_score = 4, research_domain = 'semantics' WHERE slug = '2026/01/30/equative-sentences-linguistic-and-philosophical-perspectives';
UPDATE articles SET relevance_score = 4, research_domain = 'communication theory' WHERE slug = '2026/01/30/from-contact-to-conversation-protactile-language-modality-an';
UPDATE articles SET relevance_score = 4, research_domain = 'sociolinguistics' WHERE slug = '2026/01/30/linguistics-in-germany-a-fresh-start-after-a-great-tradition';
UPDATE articles SET relevance_score = 4, research_domain = 'sociolinguistics' WHERE slug = '2026/01/30/social-meaning';
UPDATE articles SET relevance_score = 4, research_domain = 'communication theory' WHERE slug = '2026/01/30/the-meaning-and-grammar-of-pure-gestures-theoretical-insight';
UPDATE articles SET relevance_score = 4, research_domain = 'semantics' WHERE slug = '2026/01/30/the-semantics-of-degree-relatives';
UPDATE articles SET relevance_score = 3, research_domain = 'applied linguistics' WHERE slug = '2026/03/01/intrinsic-interpretability-at-parity-attention-based-rlmil-f';
UPDATE articles SET relevance_score = 4, research_domain = 'computational linguistics' WHERE slug = '2026/03/01/uzbek-language-morphology-analyser';
UPDATE articles SET relevance_score = 4, research_domain = 'sociolinguistics' WHERE slug = '2026/03/04/gen-z-language-yall-mean-aave-the-appropriation-of-african-a';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/03/12/vp-ellipsis-and-argument-structure-alternations-evidence-fro';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/03/19/cross-clausal-movement-and-its-limits';
UPDATE articles SET relevance_score = 4, research_domain = 'semantics' WHERE slug = '2026/03/19/semantic-coherence-in-noun-class-assignment-an-experimental';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/03/19/transitivity-in-flux-the-role-of-voice-and-v-in-the-syntax-o';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/03/26/bipartite-question-formation-in-smalgyax';
UPDATE articles SET relevance_score = 4, research_domain = 'semantics' WHERE slug = '2026/03/26/the-semantics-of-plural-morphology-in-akan';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/03/26/wh-interrogatives-in-camuno';
UPDATE articles SET relevance_score = 4, research_domain = 'sociolinguistics' WHERE slug = '2026/03/27/is-genderinclusive-language-leftwing-the-social-meaning-of-f';
UPDATE articles SET relevance_score = 4, research_domain = 'sociolinguistics' WHERE slug = '2026/03/31/methodological-advancements-in-dialect-identification-tasks';
UPDATE articles SET relevance_score = 4, research_domain = 'semantics' WHERE slug = '2026/04/01/countability-and-measured-parts-in-mixed-drink-nouns';
UPDATE articles SET relevance_score = 4, research_domain = 'computational linguistics' WHERE slug = '2026/04/01/employing-large-language-models-in-swahili-a-low-resource-la';
UPDATE articles SET relevance_score = 4, research_domain = 'computational linguistics' WHERE slug = '2026/04/01/integrated-bayesian-bidirectional-attention-network-for-adva';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/01/not-all-coexpressions-are-syncretisms-limiting-nanosyntax';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/01/the-law-and-order-of-selection-violating-coordination-german';
UPDATE articles SET research_domain = 'computational linguistics' WHERE slug = '2026/04/07/a-hybrid-systematic-literature-review-and-automated-content';
UPDATE articles SET relevance_score = 4, research_domain = 'phonology' WHERE slug = '2026/04/07/affective-coronal-alternations-in-mapudungun-sound-symbolism';
UPDATE articles SET relevance_score = 4, research_domain = 'morphology' WHERE slug = '2026/04/07/deconstructing-notions-of-morphological-complexity-lessons-f';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/07/intransparent-gap-relatives-in-japanese';
UPDATE articles SET relevance_score = 4, research_domain = 'morphology' WHERE slug = '2026/04/07/parsability-revisited-and-reassessed';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/07/raised-and-in-situ-preverbal-foci-a-unified-prosodic-account';
UPDATE articles SET relevance_score = 4, research_domain = 'semantics' WHERE slug = '2026/04/07/the-linguistic-factors-of-semantic-transparency-evidence-fro';
UPDATE articles SET relevance_score = 3, research_domain = 'semantics' WHERE slug = '2026/04/08/simin-karimi-narges-nematollahi-roya-kabiri-jian-gang-ngui-e';
UPDATE articles SET relevance_score = 3, research_domain = 'sociolinguistics' WHERE slug = '2026/04/10/more-seats-at-the-table-bringing-linguistics-behind-bars';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/10/peter-w-culicover--giuseppe-varaschin-deconstructing-syntact';
UPDATE articles SET relevance_score = 4, research_domain = 'sociolinguistics' WHERE slug = '2026/04/10/racially-hegemonic-articulations-class-as-race-in-constructi';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/10/svenja-krieger-word-order-variation-in-italian-and-spanish-w';
UPDATE articles SET relevance_score = 4, research_domain = 'pragmatics' WHERE slug = '2026/04/10/tim-wharton--louis-de-saussure-pragmatics-and-emotion-cambri';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/13/reconciling-animacy-and-noun-class-in-bantu';
UPDATE articles SET relevance_score = 4, research_domain = 'phonology' WHERE slug = '2026/04/13/three-arguments-for-abstraction-in-phonology';
UPDATE articles SET relevance_score = 4, research_domain = 'pragmatics' WHERE slug = '2026/04/13/two-kinds-of-singular-they-a-usage-based-model';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/20/active-participles-are-deverbal-adjectives';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/20/object-control-verbs-and-syntactic-causatives-inflected-infi';
UPDATE articles SET relevance_score = 4, research_domain = 'semantics' WHERE slug = '2026/04/20/on-the-rescuing-of-some-indefinites';
UPDATE articles SET relevance_score = 4, research_domain = 'phonology' WHERE slug = '2026/04/20/phonologization-of-cumulative-phonetic-length-in-kashubian';
UPDATE articles SET relevance_score = 4, research_domain = 'pragmatics' WHERE slug = '2026/04/20/revising-and-extending-gricean-maxims-the-trics-principles';
UPDATE articles SET relevance_score = 4, research_domain = 'communication theory' WHERE slug = '2026/04/20/ryan-nefdt-the-philosophy-of-theoretical-linguistics-a-conte';
UPDATE articles SET relevance_score = 4, research_domain = 'sociolinguistics' WHERE slug = '2026/04/20/social-threat-as-motivation-for-phonetic-divergence-evidence';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/20/syntactic-predicates';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/20/the-relation-between-head-movement-and-periphrasis';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/20/the-syntactic-constraint-on-english-auxiliary-contraction';
UPDATE articles SET relevance_score = 4, research_domain = 'phonology' WHERE slug = '2026/04/24/a-large-scale-investigation-of-vowel-co-occurrence-patterns';
UPDATE articles SET relevance_score = 4, research_domain = 'phonology' WHERE slug = '2026/04/24/competition-and-gradience-a-representational-account-of-suff';
UPDATE articles SET relevance_score = 4, research_domain = 'psycholinguistics' WHERE slug = '2026/04/24/finding-anchors-in-code-switching-how-nouns-guide-online-pro';
UPDATE articles SET relevance_score = 4, research_domain = 'historical linguistics' WHERE slug = '2026/04/24/george-aaron-broadwell-the-timucua-language-a-text-based-ref';
UPDATE articles SET relevance_score = 4, research_domain = 'psycholinguistics' WHERE slug = '2026/04/28/compositional-parsing-in-adjective-noun-phrases-the-role-of';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/04/28/genitive-alternation-in-possessives-and-beyond-morphological';
UPDATE articles SET relevance_score = 4, research_domain = 'phonology' WHERE slug = '2026/04/28/guttural-syneresis-in-tigrinya-and-tigre';
UPDATE articles SET relevance_score = 4, research_domain = 'computational linguistics' WHERE slug = '2026/05/01/from-word-to-sentence-embedding-and-beyond-bridging-the-gap';
UPDATE articles SET relevance_score = 4, research_domain = 'computational linguistics' WHERE slug = '2026/05/01/reading-between-the-lines-emotion-classification-using-sente';
UPDATE articles SET relevance_score = 4, research_domain = 'phonology' WHERE slug = '2026/05/08/backness-agreement-in-consonant--glide-onsets-evidence-from';
UPDATE articles SET relevance_score = 4, research_domain = 'phonology' WHERE slug = '2026/05/08/get-rich-quick-why-kids-dont-need-occams-razor';
UPDATE articles SET relevance_score = 4, research_domain = 'syntax' WHERE slug = '2026/05/08/when-passives-involve-no-a-movement-rethinking-indonesian-ty';
UPDATE articles SET relevance_score = 3, research_domain = 'sociolinguistics' WHERE slug = '2026/05/16/speaker-perceptions-of-americanisms-in-nigerian-english';
UPDATE articles SET relevance_score = 4, research_domain = 'sociolinguistics' WHERE slug = '2026/05/21/singlish-has-grammar-too-colonial-recursivity-in-the-constru';
UPDATE articles SET relevance_score = 4, research_domain = 'semantics' WHERE slug = '2026/05/25/object-mass-nouns-specify-individuation-lexically-evidence-f';
UPDATE articles SET relevance_score = 4, research_domain = 'psycholinguistics' WHERE slug = '2026/05/25/processing-standard-and-expletive-negation-an-eye-tracking-s';
UPDATE articles SET relevance_score = 4, research_domain = 'morphology' WHERE slug = '2026/05/25/sub-extracting-out-of-the-icelandic-aba-problem';
UPDATE articles SET relevance_score = 4, research_domain = 'sociolinguistics' WHERE slug = '2026/05/27/new-speakers-for-established-listeners-multilingual-regiment';
